apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbb
  labels:
    app: hbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbb
  template:
    metadata:
      labels:
        app: hbb
    spec:
      containers:
      - name: hbb
        image: docker.io/library/hbb:1.0.6
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http-hbb
        env:
           - name: Hbb__HostingBasePath
             valueFrom: 
               configMapKeyRef:
                 name: hbb-config
                 key: Hbb.BasePath
           - name: Hbb__GitHubToken
             valueFrom:
               secretKeyRef:
                 name: sunedoes-secrets
                 key: githubpat




